// apps/react/src/components/EventMap.tsx
import { MapContainer, TileLayer, CircleMarker, Popup } from 'react-leaflet';
import { Link } from 'react-router-dom';
import type { EarthquakeFeature, EonetEvent } from '@terrawatch/shared';
import type { LatLngExpression } from 'leaflet';

interface EventMapProps {
  earthquakes: EarthquakeFeature[];
  eonetEvents: EonetEvent[];
}

function getDepthColor(depth: number) {
  if (depth < 30) return '#f97316';
  if (depth < 100) return '#eab308';
  if (depth < 300) return '#22c55e';
  return '#3b82f6';
}

function getCategoryColor(categoryId: string) {
  const colors: Record<string, string> = {
    wildfires: '#ef4444',
    severeStorms: '#8b5cf6',
    volcanoes: '#f97316',
    seaLakeIce: '#06b6d4',
    snow: '#06b6d4',
  };
  return colors[categoryId] || '#6b7280';
}

function EventMap({ earthquakes, eonetEvents }: EventMapProps) {
  const center: LatLngExpression = [20, 0];

  return (
    <MapContainer
      center={center}
      zoom={2}
      className="h-[500px] w-full overflow-hidden rounded-xl shadow-sm ring-1 ring-gray-100"
    >
      <TileLayer
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />

      {earthquakes.map((eq) => {
        const [lon, lat, depth] = eq.geometry.coordinates;
        const mag = eq.properties.mag ?? 1;
        const color = getDepthColor(depth);
        const radius = Math.max(mag * 3, 4);

        return (
          <CircleMarker
            key={eq.id}
            center={[lat, lon]}
            radius={radius}
            pathOptions={{ color, fillColor: color, fillOpacity: 0.6 }}
          >
            <Popup>
              <div className="text-sm">
                <p className="font-bold">M{mag.toFixed(1)}</p>
                <p>{eq.properties.place}</p>
                <p>Depth: {depth.toFixed(1)} km</p>
                <p>{new Date(eq.properties.time).toLocaleString()}</p>
                <Link
                  to={`/event/${eq.id}`}
                  className="text-indigo-600 hover:underline"
                >
                  View details
                </Link>
              </div>
            </Popup>
          </CircleMarker>
        );
      })}

      {eonetEvents.map((event) => {
        if (event.geometry.length === 0) return null;
        const geo = event.geometry[event.geometry.length - 1];
        const [lon, lat] = geo.coordinates;
        const categoryId = event.categories[0]?.id || '';
        const color = getCategoryColor(categoryId);

        return (
          <CircleMarker
            key={event.id}
            center={[lat, lon]}
            radius={8}
            pathOptions={{ color, fillColor: color, fillOpacity: 0.6 }}
          >
            <Popup>
              <div className="text-sm">
                <p className="font-bold">{event.title}</p>
                <p>Category: {event.categories[0]?.title || 'Unknown'}</p>
                <p>Status: {event.closed ? 'Closed' : 'Open'}</p>
                <Link
                  to={`/event/${event.id}`}
                  className="text-indigo-600 hover:underline"
                >
                  View details
                </Link>
              </div>
            </Popup>
          </CircleMarker>
        );
      })}
    </MapContainer>
  );
}

export default EventMap;

// apps/vue/src/components/EventMap.vue
<script setup lang="ts">
import {
  LMap,
  LTileLayer,
  LCircleMarker,
  LPopup,
} from '@vue-leaflet/vue-leaflet';
import { RouterLink } from 'vue-router';
import type { EarthquakeFeature, EonetEvent } from '@terrawatch/shared';

defineProps<{
  earthquakes: EarthquakeFeature[];
  eonetEvents: EonetEvent[];
}>();

function getDepthColor(depth: number) {
  if (depth < 30) return '#f97316';
  if (depth < 100) return '#eab308';
  if (depth < 300) return '#22c55e';
  return '#3b82f6';
}

function getCategoryColor(categoryId: string) {
  const colors: Record<string, string> = {
    wildfires: '#ef4444',
    severeStorms: '#8b5cf6',
    volcanoes: '#f97316',
    seaLakeIce: '#06b6d4',
    snow: '#06b6d4',
  };
  return colors[categoryId] || '#6b7280';
}
</script>

<template>
  <div
    class="h-[500px] w-full overflow-hidden rounded-xl shadow-sm ring-1 ring-gray-100"
  >
    <LMap :zoom="2" :center="[20, 0]" style="height: 100%; width: 100%">
      <LTileLayer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
      />

      <LCircleMarker
        v-for="eq in earthquakes"
        :key="eq.id"
        :lat-lng="[eq.geometry.coordinates[1], eq.geometry.coordinates[0]]"
        :radius="Math.max((eq.properties.mag ?? 1) * 3, 4)"
        :color="getDepthColor(eq.geometry.coordinates[2])"
        :fill-color="getDepthColor(eq.geometry.coordinates[2])"
        :fill-opacity="0.6"
      >
        <LPopup>
          <div class="text-sm">
            <p class="font-bold">M{{ (eq.properties.mag ?? 1).toFixed(1) }}</p>
            <p>{{ eq.properties.place }}</p>
            <p>Depth: {{ eq.geometry.coordinates[2].toFixed(1) }} km</p>
            <p>{{ new Date(eq.properties.time).toLocaleString() }}</p>
            <RouterLink
              :to="`/event/${eq.id}`"
              class="text-indigo-600 hover:underline"
            >
              View details
            </RouterLink>
          </div>
        </LPopup>
      </LCircleMarker>

      <template v-for="event in eonetEvents" :key="event.id">
        <LCircleMarker
          v-if="event.geometry.length > 0"
          :lat-lng="[
            event.geometry[event.geometry.length - 1].coordinates[1],
            event.geometry[event.geometry.length - 1].coordinates[0],
          ]"
          :radius="8"
          :color="getCategoryColor(event.categories[0]?.id || '')"
          :fill-color="getCategoryColor(event.categories[0]?.id || '')"
          :fill-opacity="0.6"
        >
          <LPopup>
            <div class="text-sm">
              <p class="font-bold">{{ event.title }}</p>
              <p>Category: {{ event.categories[0]?.title || 'Unknown' }}</p>
              <p>Status: {{ event.closed ? 'Closed' : 'Open' }}</p>
              <RouterLink
                :to="`/event/${event.id}`"
                class="text-indigo-600 hover:underline"
              >
                View details
              </RouterLink>
            </div>
          </LPopup>
        </LCircleMarker>
      </template>
    </LMap>
  </div>
</template>
